### ISSUE TITLE
Broken hyperlink on "gh-pages" site

### ISSUE THREAD

**Issue by ottta** [googlefonts/googlefonts-project-template#103]
There's directive hyperlink to `proof/*.html` but we don't have any direct html files inside the root `./proof` directory, instead we have another directory that contains html files

![Screenshot 2023-05-22 at 18 08 57](https://github.com/googlefonts/googlefonts-project-template/assets/38872319/3ab10b80-15d2-4c8c-b0a1-12c641bc1cfe)

And here's an example video:

https://github.com/googlefonts/googlefonts-project-template/assets/38872319/3e53a1cc-a8da-436c-bdc4-55207e492a3b

**Comment by simoncozens** [comment]
Ah, OK, this looks to be because we changed the software that's making proofs. Ideally it will also generate an index to the proof pages it generates.

**Comment by simoncozens** [comment]
gftools calls diffenator2 now (this is the change which meant it was working before but isn't working now), so we need to fix it there.

**Comment by m4rc1e** [comment]
Still working on it I'm afraid. Will ping this issue once it's done. May add a temporary `index`.html` temp page for now.

**Comment by ottta** [comment]
> Still working on it I'm afraid. Will ping this issue once it's done. May add a temporary `index`.html` temp page for now.

Thank you for paying attention to this issue, I can't collaborate yet to the diffenator2 because I still can't get the logic of the algorithm, especially for generating gh-pages related data

**Comment by m4rc1e** [comment]
Apologies for the delay. I've started working on this. Should be ready by EOD.
