### ISSUE TITLE
Support multiple gf families in 1 repo?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlefonts-project-template#106]
I saw this week 2 projects with multiple gf families in 1 repo, which the gh action on this template doesn't support. What might be the best way to support such repos with multiple families?

* https://github.com/jenskutilek/homecomputer-fonts
* https://github.com/SorkinType/Briem-Hand

**Comment by simoncozens** [comment]
Noto repos have some simple changes to make this happen. I'll backport them.
