### ISSUE TITLE
update-project-template requires node

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/googlefonts-project-template#112]
Which not everyone has! So we need to add something about this to the README.

**Comment by vv-monsalve** [comment]
When brew installing, it's requiring to change the ownership of some directories by running extra commands that require a sudo login. 

Do you think we should tell the users about that possibility? I mean adding a line into the instructions like _When installing Node, it may be necessary to change certain permissions that require sudo login. Please follow the instructions provided in terminal_

````
You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/share/man/man8

And make sure that your user has write permission.
  chmod u+w /usr/local/share/man/man8
````
