### ISSUE TITLE
Add .plist files for all language sets to the sources folder

### ISSUE THREAD

**Issue by agyeiarcher** [googlefonts/googlefonts-project-template#117]
May make it easier for some users to quickly ramp up projects, esp for tricker sets like GF Latin African. Currently they can be found and extrapolated from the Glyph sets [here](https://github.com/googlefonts/glyphsets/tree/ce0203ca3d6276dcf4c9c9af95aee2b58db4afb7/GF_glyphsets/Latin/glyphs) but having them in the core source repo can save some steps

**Comment by eliheuer** [comment]
Thanks! Good idea, I'll look into this.

**Comment by agyeiarcher** [comment]
Is it possible for me to have made a PR for this? I think I tried but not
sure if I made an error. I'm happy to upload them or just send via email

**Comment by eliheuer** [comment]
I just looked through the old issues and PR and couldn't find anything. But feel free to make a new PR or just describe exactly what you want here and I'll try to do it.

**Comment by agyeiarcher** [comment]
I'll work on it tonight and see if I can do it (I need the practice). Will
send the plists to you otherwise

AA

**Comment by eliheuer** [comment]
That would be great thanks, one or more people familiar with this repo will review the PR, so no need to be perfect, check the "allow edits by maintainers" box when you make the PR and reviewers can push fixes to your branch if needed.

**Comment by simoncozens** [comment]
Thanks for this, Agyei!
