### ISSUE TITLE
`make images`: ModuleNotFoundError: No module named 'drawbot_skia'

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/googlefonts-project-template#123]
I get this error in the current template:

```
▶ make images
python3 documentation/image1.py --output documentation/image1.png
Traceback (most recent call last):
  File "/Special-Gothic/documentation/image1.py", line 8, in <module>
    from drawbot_skia.drawbot import *
ModuleNotFoundError: No module named 'drawbot_skia'
make: *** [documentation/image1.png] Error 1
```

**Comment by eliheuer** [comment]
This is a problem with how the project template sets up the Python virtual environment and not DrawBot-Skia.

I'm looking into it.

**Comment by eliheuer** [comment]
I made a PR here that fixes this: https://github.com/googlefonts/googlefonts-project-template/pull/124

**Comment by eliheuer** [comment]
@weiweihuanghuang This was fixed with this PR that was merged: https://github.com/googlefonts/googlefonts-project-template/pull/124

Run `make update-project-template` to get the latest updates.
