### ISSUE TITLE
first-run script is fragile with repository name-changes

### ISSUE THREAD

**Issue by n8willis** [googlefonts/googlefonts-project-template#125]
The first-run script does some setup that is dependent on the repo name (specifically I'm thinking of the badges / proof URL auto-configuration).

Unfortunately, people sometimes change the name of their repo — and there's no way to prevent them from doing so. I think there are legitimate reasons for needing to do that, such as typos or changing from Foo to Foo-Font or Foo-Regular or Foo-Libre, etc., etc.

Whenever someone does such a repo name change, the autoconfig'ed stuff that used the previous repo-name as a string is now broken, including the buttons on the README.

Ideally, either of these two fixes could resolve the breakage:
1. Have the first-run or some other script triggered on a repo name-change and fix any config that is dependent on the repo-name as a string
2. Include some user-visible HOWTO or documentation noting that this side-effect can happen on a name change, and telling users what they should do to fix it.

And, of course, there could be some other solutions. But the breakage is a real-world-observable problem.

**Comment by simoncozens** [comment]
I'm going to replace this with a Makefile target that the user runs to "customise" the build, and can rerun when necessary.
