### ISSUE TITLE
Fonts artifacts zip shows virus alert in Windows 10

### ISSUE THREAD

**Issue by xconsau** [googlefonts/googlefonts-project-template#168]
I am using the googlefonts-project-template for one of my fonts "[Cause](https://github.com/xconsau/Cause/)" . When I try to download the artifacts zip file, the Windows security center alerts me if a virus and automatically deletes the downloaded zip file. Please see attached screenshot.

![artifacts](https://github.com/googlefonts/googlefonts-project-template/assets/11784237/8e78c7a3-17d1-4058-9ce6-ee81f7480cb1)

Artifacts link: https://github.com/xconsau/Cause/actions/runs/8642807521

Upon checking the details of the virus, I found that it is a Trojan located inside the proof HTML files. See attached screenshot:

![trojan](https://github.com/googlefonts/googlefonts-project-template/assets/11784237/8f1f921d-389d-497c-976d-e5aa7cb2759a)

**Comment by simoncozens** [comment]
This is a false positive. There is nothing unusual or suspicious about the HTML and Javascript in the proof file; the nice thing about HTML files is that you can inspect them yourself and confirm this!

The "H" stands for "heuristic" and the "ML" stands for "machine learning", which means that Windows Defender is hallucinating here. I found for "wacatac h ml" on the Internet was (a) people complaining about false positives, and (b) this impressively useless ["threat description"](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.H!ml&threatid=2147814524) from Microsoft. Not our bug!

**Comment by xconsau** [comment]
Thank you for the swift response, Simon. I added an exclusion rule for the Windows defender for the artifacts zip file. Nothing unusual was found in the download. Thanks once again.
