### ISSUE TITLE
My repository URL doesn’t match customize.py expectations 

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/googlefonts-project-template#177]
When I run `make customize` I get the following:

```
. venv/bin/activate; python3 scripts/customize.py
My git repository URL (https://guidoferreyra@github.com/guidoferreyra/Geist.git
) didn't look what I expected - are you hosting this on github?
You will need to do the initialization steps manually.
Read scripts/customize.py for more instructions how to do this.
```

Any ideas, thanks!

**Comment by am-v** [comment]
Hi @guidoferreyra, Greetings! 

The customize.py function expects the Git remote URL to start with either `https://github.com/` or `git@github.com`. However, in your case, the remote URL format includes your GitHub username in the path, like https://[my-user-name]@github.com/[my-user-name]/[reponame].git.

Could you please check your current remote URL using the following command?
```git remote -v```

If necessary, you can update the Remote URL to the correct format using the command:
```git remote set-url origin git@github.com:[my-user-name]/[reponame].git```

After making this change, verify the updated remote URL with:
```git remote -v```

This adjustment should resolve the issue.

Cheers!

**Comment by guidoferreyra** [comment]
This worked perfectly, thanks!
