### ISSUE TITLE
GitHub Actions doesn't work with private repositories

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/googlefonts-project-template#19]
I'm working on some fonts hosted in a private GitHub repository, I set up the Google Font Unified Font Repository for that repo, but I get the following error in the Actions tab of the GitHub page:
>GitHub Actions workflows can't be executed on this repository.
The billing plan for ********** does not include access to GitHub Actions. Please contact the organization owner or billing manager for questions about the current billing plan.

More info about this from GitHub is here: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

>GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account. Any usage beyond the included amounts is controlled by spending limits. If you are a monthly-billed customer, your account will have a default spending limit of $0, which prevents additional usage of minutes or storage for private repositories beyond the amounts included with your account.

I foresee this causing problems in the future. The local build currently doesn't work for me when following the build instructions. I made an issue about the first build error I had here: https://github.com/googlefonts/Unified-Font-Repository/issues/20

**Comment by simoncozens** [comment]
So, if you want actions on private repos, you have to pay? That... doesn't seem like a problem? I'll try and sort the M1 issue though.

**Comment by eliheuer** [comment]
The idea is to reduce friction in the system. The private repo might belong to a large organization where getting something like this approved would take a long time, or it could be a single designer with no budget.

**Comment by PeterDekkers** [comment]
These days GitHub include 2,000 minutes/month in free plans, to use GitHub Actions in private repos. In public repos using GitHub Actions is free.
