### ISSUE TITLE
Should we make the readme instructions more verbose?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/googlefonts-project-template#45]
Everyone is probably groaning at this suggestion but I feel some steps are missing for people who do not understand how Github works. This is especially true for type designers who do not fit into the developer 'mould' so to speak. Perhaps Eli can make a really cool youtube video?

**Comment by simoncozens** [comment]
I've added some more verbosity, but people are going to have a hard time hosting a repo on GitHub if they don't know how GitHub works, so there's only so much we can/should do.
