### ISSUE TITLE
[docs] Add a link to the talk by Sascha Brawer & Werner Lemberg about ttfautohing and GNU Make

### ISSUE THREAD

**Issue by twardoch** [googlefonts/googlefonts-project-template#67]
In this talk from TYPO Labs 2017, Sascha Brawer & Werner Lemberg talk about ttfautohint & the Noto fonts, and Werner spends almost a half of the talk (from 23:18) explaining GNU Make and the Makefiles: [https://youtu.be/LZ-PZDy8WHY?t=1418](https://youtu.be/LZ-PZDy8WHY?t=1418) — this is a good basic intro to how Makefiles work, and it’s quite relevant to fonts, so it’d be good to somehow include it in the docs for this repo.

**Comment by simoncozens** [comment]
It's a nice idea, but I think not; if people *need* to know how Makefiles work, we've already failed, and should be making things easier for them.
