### ISSUE TITLE
clean command should maybe use `-delete` switch instead

### ISSUE THREAD

**Issue by madig** [googlefonts/googlefonts-project-template#74]
The current Makefile uses

https://github.com/googlefonts/googlefonts-project-template/blob/d66be4c457b4974fb59e575b0b1f38912dc5becf/Makefile#L46

which

1. blows up if there's nothing to clean
2. has a spurious "delete" word, which also blows up `rm`

It should maybe do `find . -name "*.pyc" -delete` instead, see https://unix.stackexchange.com/questions/167823/finds-exec-rm-vs-delete.

**Comment by eliheuer** [comment]
I just tested this and was not able to get it to "blow up" with the current implementation. What can I do to make it blow up?

But this seems like a possible UX improvement and the issue should be addressed & closed or implemented.
