### ISSUE TITLE
`make update` command broken

### ISSUE THREAD

**Issue by madig** [googlefonts/googlefonts-project-template#75]
The Makefile contains

https://github.com/googlefonts/googlefonts-project-template/blob/d66be4c457b4974fb59e575b0b1f38912dc5becf/Makefile#L52

but the `$(dependency)` variable is undefined. Running pip then crashes (after activating the venv, which isn't done like in the build command):

```
pip install --upgrade ; pip freeze > requirements.txt
ERROR: You must give at least one requirement to install (see "pip help install")
```

I also find the in-place updating of requirements a bit unfortunate. It perpetuates dependencies even if they're not used anymore because the primary/transient distinction gets lost. A cleaner way would be to have a file requirements.in:

```
fontmake>=2.4
fontbakery>=0.8
gftools[qa]>=0.7
drawbot-skia>=0.4.8
sh>=1.14.2
bumpfontversion>=0.2.0
```

and use `pip-compile requirements.in` (https://github.com/jazzband/pip-tools) to generate the actual requirements.txt with all pinned deps.

**Comment by wayne-shih** [comment]
I had a similar issue but via workflow actions 
As an interim workaround I changed my requirements.txt to a previously (known stable, at least for me) generated file
[requirements.txt](https://github.com/googlefonts/googlefonts-project-template/files/8796882/requirements.txt)

major version changes in requirements.txt from previous stable to new generated... 
```diff
-    cattrs==1.10.0
-    certifi==2021.10.8
+    cattrs==22.1.0
+    certifi==2022.5.18.1

     ...

-    exceptiongroup==1.0.0rc7

     ...

-    protobuf==3.20.1
+    protobuf==4.21.1
```
wonder if there's any breaking changes in those deps that's causing the issue. 
on a side note, also noticed exceptiongroup got removed in the new generated req txt

**Comment by simoncozens** [comment]
Thank you for the PR; I finished it off in #169.
