### ISSUE TITLE
Contributors vs Authors?

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/googlefonts-project-template#76]
I'm still a bit confused by this, if I make a derivative work based off an OFL font, in the new repo would my name go in both AUTHORS.TXT and CONTRIBUTORS.TXT or only CONTRIBUTORS.TXT?

Who becomes a copyright author - is that anyone who has made changes to a project?

**Comment by simoncozens** [comment]
The distinction between authors and contributors is mainly about [human authors versus *corporate* copyright holders](https://github.com/googlefonts/fontbakery/issues/2111#issuecomment-431716622). When there are no corporate assignments involved, names go in both files.

I believe that for derivative works from an OFL project, the bits your author are your copyright, so you get added to AUTHORS too. But I am not totally sure; check with @davelab6.

**Comment by weiweihuanghuang** [comment]
Thanks. Just so I understand correctly, when I make a derivative project based on an OFL font I can add my name and the original copyright authors into the authors list?

Also in the font’s designer metadata section, what do you think makes sense to put there?

**Comment by wayne-shih** [comment]
from my understanding, for derivative projects...

yes to adding your own name in the authors list. (I would add it to both authors and contributors txt files) 
if it's a big enough derivative, what i've done in the past is do a clean authors list with just my name and moved everyone else to contributors list 

re font designer metadata. I've previously done it so it includes my name plus whatever is currently on there (or just my name if it's a big enough derivative) (or keep it as is if the derivative is essentially a patch or a small tweak) 

also note, always add in the original author and copyrighted author line in the description metadata (good practice for open source softwares and it satisfies the attribution clause from memory) and the fact that the new font is a derivative of the original font with a link to it if available.
