### ISSUE TITLE
Build errors with exit code 2 on initial commit when creating a new repository from googlefonts-project-template

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/googlefonts-project-template#81]
I clicked the green "Use this template" button at commit [e92c1c8](https://github.com/googlefonts/googlefonts-project-template/commit/e92c1c8b2fd84520c4c638150793c550266d9cd9) to start a new font project and noticed that the initial commit build returns an error.

<img width="735" alt="error01" src="https://user-images.githubusercontent.com/5162664/187976077-28a14723-99fe-4bfd-918e-13c7c4012dbc.png">

This could be confusing for people less familiar with this system than I am. The fonts build, but a new user might not understand that the font output is still good despite the error.

<img width="517" alt="error02" src="https://user-images.githubusercontent.com/5162664/187976102-abcde4d9-654f-45a6-beb2-23b7706f41cd.png">

**Comment by weiweihuanghuang** [comment]
I got tihs error too, and it failed to produce the release? Did I do something wrong?

**Comment by eliheuer** [comment]
This was fixed in PR #93

**Comment by weiweihuanghuang** [comment]
How do I update my repo to the latest version of the template 😅

**Comment by weiweihuanghuang** [comment]
Oh never mind I see the update instruction in the readme!
