### ISSUE TITLE
Hataf Hebrew diacritics in default example font `Rubik.glyphs` are broken.

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/googlefonts-project-template#85]
`hatafsegol-hb, U+05B1` should look something like this: 

<img width="291" alt="Hataf-Segol" src="https://user-images.githubusercontent.com/5162664/191409712-c1b5e3a5-a976-4c34-9902-050e68f7edd8.png">

But in the file `Rubik.glyphs` the dots are overlapping creating a blob that displays an incorrect shape:

<img width="258" alt="Hataf-Segol-Bad" src="https://user-images.githubusercontent.com/5162664/191410195-67ff653d-6bc6-4189-8565-a03402a9ec14.png">

The same problem exists for all Hataf Hebrew diacritics, `hatafsegol-hb` `hatafpatah-hb` `hatafqamats-hb` in both regular and italic styles.

**Comment by eliheuer** [comment]
I made an issue for this in the upstream repo as well: https://github.com/googlefonts/rubik/issues/49

**Comment by simoncozens** [comment]
I think that’s a good place for it. Since the first thing people will do with this repo is rip out Rubio and out their own font in, I’m not sure it’s a problem for us.

**Comment by eliheuer** [comment]
I'm thinking about how non-experts will use this repo. I think many people will and do use the default font as a reference for best practices around how to set up a glyphs file.
