### ISSUE TITLE
Outline Correctness Badge

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/googlefonts-project-template#88]
A font can get a fairly low score for the 'outline correctness' if it simply is a design that deviates from common Google fonts designs. 

I don't think the badge needs to be on a repo, if someone doesn't understand exactly how it works it they might assume it's an objective measure for the quality of a font's outlines.

**Comment by eliheuer** [comment]
I agree, by default, It's the first thing people see in the repo, [I moved the badges to the bottom of one of my repos](https://github.com/eliheuer/GTL001#google-fonts-qa) for this and other similar reasons.
