### ISSUE TITLE
Please make the instructions for accessing --full-lists more explicit

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/googlefonts-project-template#90]
I would like to use the full lists in a script font I am checking to make sure no joins are missing. But I can quite figure out what file needs the command "--full-lists" added to it and even if I did sort that out I might not know where it goes after I find it. Thanks!

**Comment by eliheuer** [comment]
@EbenSorkin I just merged a pull-request that makes `--full-lists` the default behavior: https://github.com/googlefonts/googlefonts-project-template/pull/92

All new repositories will show `--full-lists` by default, and to update old repositories you can run `make update-project-template` from the root of the Git repository and everything should update.

Thanks!
