### ISSUE TITLE
Move build command into build.sh

### ISSUE THREAD

**Issue by yanone** [googlefonts/googlefonts-project-template#94]
I wish that the "automatic" parts of this repository (Git Actions, Makefile) should remain untouched by people as much as possible, especially in regards to updating people’s repo structure from the upstream template.

Therefore I suggest to create a `build.sh` file and referencing that in `Makefile` instead of hard-coding `gftools builder` directly in `Makefile`. This allows a much greater deal of freedom to customize the build commands with pre/afterburners or the likes without touching the `Makefile`.

I could prepare a PR.

**Comment by m4rc1e** [comment]
What about allowing the builder to accept post processing scripts e.g

```YAML
name: My Font
postprocessor: process_fonts.py # this gets run at the end. 
```

**Comment by yanone** [comment]
As long as they can be any shell commands and we're doing both pre and post stages, it's kind of the same result. Where they are defined is just a matter of taste.

My main aim here is to separate the user-facing files as cleanly as possible from the Actions-facing files, cause they’re confusing, kind of hard-wired, and should never even be visible to novice users. And they need to be cleanly and reliably updateable from upstream. As soon as I can see more ways to enhance the separation, I will say so. Also if you can think of ways to separate that further, please consider taking this action. With the repo template, we really need to make sure that it can be operated by novices. The people who are using the repo today in reality are people who have never seen a command line.

**Comment by simoncozens** [comment]
1) Builder2 is the long-term way forward here.
2) People can of course add lines to the `build` Make target if they want to.
