### ISSUE TITLE
Trigger releases through tags

### ISSUE THREAD

**Issue by yanone** [googlefonts/googlefonts-project-template#95]
Please make it possible to trigger a font release through commit tags.
I wish I could help but I have no idea how this works.

**Comment by simoncozens** [comment]
So we do this in Noto, and it works very nicely. This should be part of a bigger conversation about folding back some of the Noto CI magic (e.g. tags for releases, automated GF PRs) into expressive library projects based on this repo; the question really would be how much we want and how much is appropriate. Probably @m4rc1e and I should have a chat about this (others welcome to join, of course).

I think step one of that conversation is (strangely) merging the ninja branch of gftools into main; currently Noto has its own gftools branch and it would be good to unify that first.

**Comment by simoncozens** [comment]
I implemented this.
