### ISSUE TITLE
Template seems to be broken

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/googlefonts-project-template#99]
When I use the link to make a new template based repo the inital build ends in this error.

> Error: Invalid status code: 128
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
>     at ChildProcess.emit (node:events:[52](https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7221240977#step:7:53)7:28)
>     at maybeClose (node:internal/child_process:1092:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

I thought maybe if I added files for the process to chew on this would resolve it but so far I have not been able see that work and the same error pops up.

Could the repo revert to a last working version?

**Comment by simoncozens** [comment]
Grrr, I think it's related to this: https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

**Comment by m4rc1e** [comment]
I just reran the ci on this repo and it was fine, https://github.com/googlefonts/googlefonts-project-template/actions/runs/4055189166

@EbenSorkin can I have the url for the broken repo please?

**Comment by simoncozens** [comment]
> I just reran the ci on this repo and it was fine

Sure, the change doesn't affect existing repos, just new ones.

**Comment by m4rc1e** [comment]
Thanks Simon. My bad, just read your link

> This change will not impact any existing enterprises, organizations or repositories. Here is how the defaults are set going forward.

@EbenSorkin add me as a contributor to your repo. I'll then make a fix and if it works well, migrate it to this repo as well.

**Comment by EbenSorkin** [comment]
Ok I'll invite you today. Thank you!

**Comment by EbenSorkin** [comment]
Hey Marc! Thanks!

You are invited.

I assume that at some point later the template itself will be resolved. No?

-e.

**Comment by m4rc1e** [comment]
Alright, we have two options.

As Simon pointed out, the issue is being caused by the action `stefanzweifel/git-auto-commit-action`. We could either do our own version of this action, something like

```YAML

- name First-run setup
  run: |
    git config --global user.name "GF Bot"
    git config --global user.email "bot@googlefonts.com"
    make .init.stamp
    git add .init.stamp README.md requirements.txt OFL.txt
    git commit -m "Personalize for this repo"
    git push origin $GITHUB_REF_NAME:$GITHUB_REF_NAME
```

or, we can ask that users enable the following setting in their repo once forked:

<img width="765" alt="Screenshot 2023-02-16 at 10 57 16" src="https://user-images.githubusercontent.com/7525512/219346416-5961a6dd-0b57-445a-a3ea-a470c315f7db.png">

@simoncozens thoughts?

**Comment by simoncozens** [comment]
If the first one works, it's easier...

**Comment by simoncozens** [comment]
I have a nice finesse we can do here, too. If we change "touch init.stamp" to "echo done > init.stamp", we can make this whole job conditional on:

```yaml
if: ${{ hashFiles('init.stamp') == "" }}
```

**Comment by m4rc1e** [comment]
Nice but slight issue, my manual steps don't work either

```
remote: Permission to m4rc1e/Briem-Hand-Guides.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/m4rc1e/Briem-Hand-Guides/': The requested URL returned error: 403
```

I did all the steps I listed above but it sadly failed on the `git push` step.

**Comment by simoncozens** [comment]
Yeah, I'm not very surprised. OK, we'll have to add it to the readme.

**Comment by EbenSorkin** [comment]
So you both agree then that adjusting te permissions is the right way to go
at least for the moment - correct?

-e.

**Comment by m4rc1e** [comment]
Yep ;-)

**Comment by EbenSorkin** [comment]
I'll give that a go. Thank you!

-e.

**Comment by EbenSorkin** [comment]
I tied it but got this fail.

I'll try deleting the repo and starting from the template fresh, change the
permissions and see if that works.

##[debug]git push origin
98
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:99>To
https://github.com/EbenSorkin/Briem-Hand-Guides
99
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:100>
! [rejected] main -> main (non-fast-forward)
100
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:101>error:
failed to push some refs to 'https://github.com/EbenSorkin/Briem-Hand-Guides'

101
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:102>hint:
Updates were rejected because the tip of your current branch is behind
102
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:103>hint:
its remote counterpart. Integrate the remote changes (e.g.
103
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:104>hint:
'git pull ...') before pushing again.
104
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:105>hint:
See the 'Note about fast-forwards' in 'git push --help' for details.
105
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:106>Error:
Invalid status code: 1
106
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:107>
at ChildProcess.<anonymous>
(/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)

107
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:108>
at ChildProcess.emit (node:events:527:28)
108
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:109>
at maybeClose (node:internal/child_process:1092:16)
109
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:110>
at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
{
110
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:111>
code: 1
111
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:112>}

112
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:113>Error:
Invalid status code: 1
113
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:114>
at ChildProcess.<anonymous>
(/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)

114
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:115>
at ChildProcess.emit (node:events:527:28)
115
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:116>
at maybeClose (node:internal/child_process:1092:16)
116
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:117>
at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
117
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:118>##[debug]Node
Action run completed with exit code 1
118
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:119>##[debug]Set
output changes_detected = true
119
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:120>##[debug]Set
output commit_hash = 2e06dfc29bddb65aab3c7fe33a9d801574407501
120
<https://github.com/EbenSorkin/Briem-Hand-Guides/actions/runs/4171372210/jobs/7285581682#step:7:121>##[debug]Finishing:
First-run setup

**Comment by EbenSorkin** [comment]
That did work!

Thank you!
